### PR TITLE
python3 compatible

### PR DESCRIPTION
**Pull request by varnion**
made the qt-like API compatible with both python3 and python2 (worked for me on python2.7, 3.5)

### CODE REVIEW

**Comment by varnion** [comment]
this should close issue #3

**Comment by varnion** [comment]
@astraw, would you like me to change something to make this PR acceptable?

Best Regards,
Bruno FS

**Comment by basnijholt** [comment]
Why isn't this merged yet?

**Comment by dhimmel** [comment]
Confirming that I was able to combine two SVGs with https://github.com/varnion/svg_stack/commit/d324a93a42d80c98a2ed27e4004a1781b44ffc0a in Python 3.6.

@astraw please merge or at least take a look!!!

**Comment by varnion** [comment]
I'm closing this to cleanup my personal list of open pull requests.

**Pull request closed without merging**
